---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - karo.jeeatwork.com
  resources:
  - restartrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karo.jeeatwork.com
  resources:
  - restartrules/finalizers
  verbs:
  - update
- apiGroups:
  - karo.jeeatwork.com
  resources:
  - restartrules/status
  verbs:
  - get
  - patch
  - update
