{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "karo.name" . }}-role
  labels:
    {{- include "karo.labels" . | nindent 4 }}
rules:
# Permissions for ConfigMaps
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
# Permissions for Secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
# Permissions for Deployments
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - patch
  - update
# Permissions for StatefulSets (as they can also be restart targets)
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - patch
  - update
# Permissions for RestartRule custom resources
- apiGroups:
  - karo.jeeatwork.com
  resources:
  - restartrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karo.jeeatwork.com
  resources:
  - restartrules/status
  verbs:
  - get
  - patch
  - update
{{- end }}